-- Supabase SQL schema definition for DummyJSON Products API
-- Matches fields from https://dummyjson.com/products

-- 1. Create products table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY, -- Matches the integer ID from DummyJSON
    title TEXT NOT NULL,
    slug TEXT UNIQUE, -- Custom slug column
    description TEXT,
    category TEXT,
    price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    discount_percentage NUMERIC(5, 2) DEFAULT 0.00,
    rating NUMERIC(3, 2) DEFAULT 0.00,
    stock INTEGER NOT NULL DEFAULT 0,
    brand TEXT,
    sku TEXT UNIQUE,
    weight INTEGER,
    
    -- Dimensions (flattened from dimensions object)
    dimension_width NUMERIC(10, 2),
    dimension_height NUMERIC(10, 2),
    dimension_depth NUMERIC(10, 2),
    
    warranty_information TEXT,
    shipping_information TEXT,
    availability_status TEXT,
    return_policy TEXT,
    minimum_order_quantity INTEGER DEFAULT 1,
    
    -- Meta Information (flattened from meta object)
    meta_created_at TIMESTAMPTZ,
    meta_updated_at TIMESTAMPTZ,
    meta_barcode TEXT,
    meta_qrcode TEXT,
    
    -- Arrays for tags and images
    tags TEXT[] DEFAULT '{}',
    images TEXT[] DEFAULT '{}',
    thumbnail TEXT,
    
    -- Audit Timestamps
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create product_reviews table (One-to-many relationship with products)
CREATE TABLE IF NOT EXISTS product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    rating INTEGER CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    date TIMESTAMPTZ,
    reviewer_name TEXT,
    reviewer_email TEXT,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS) for Supabase best practices
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_reviews ENABLE ROW LEVEL SECURITY;

-- 4. Create Security Policies (allowing public read, authenticated insert/update)
CREATE POLICY "Allow public read access to products" ON products
    FOR SELECT USING (true);

CREATE POLICY "Allow public read access to product reviews" ON product_reviews
    FOR SELECT USING (true);

-- 5. Create trigger to automatically handle updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
