-- SQL Schema for Wishlist items in the e-commerce system
-- Links user IDs to public.users(id) and product IDs to products(id)

CREATE TABLE IF NOT EXISTS public.wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Ensure a user can only have a single record for a specific product in their wishlist
    UNIQUE (user_id, product_id)
);

-- Enable RLS for wishlist_items
ALTER TABLE public.wishlist_items ENABLE ROW LEVEL SECURITY;

-- RLS Policies for wishlist_items
CREATE POLICY "Users can manage their own wishlist items" ON public.wishlist_items
    FOR ALL USING (auth.uid() = user_id);
